/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_isi.ii;


import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author ramon
 */
public class Vista_10 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana8
     */
    public Vista_10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsuario1 = new javax.swing.JTextField();
        tfContraseña3 = new javax.swing.JTextField();
        tfContraseña7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FechaCrearActividad_Vista10 = new com.toedter.calendar.JDateChooser();
        HoraFinCrearActividad_Vista10 = new javax.swing.JTextField();
        Aceptar_Vista10 = new javax.swing.JButton();
        Cancelar_Vista10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        HoraInicioCrearActividad_Vista10 = new javax.swing.JTextField();

        tfContraseña3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña3ActionPerformed(evt);
            }
        });

        tfContraseña7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hora inicio:");

        jLabel2.setText("Fecha:");

        HoraFinCrearActividad_Vista10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraFinCrearActividad_Vista10ActionPerformed(evt);
            }
        });

        Aceptar_Vista10.setBackground(new java.awt.Color(0, 51, 255));
        Aceptar_Vista10.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar_Vista10.setText("Aceptar");
        Aceptar_Vista10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar_Vista10ActionPerformed(evt);
            }
        });

        Cancelar_Vista10.setBackground(new java.awt.Color(0, 51, 255));
        Cancelar_Vista10.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar_Vista10.setText("Cancelar");
        Cancelar_Vista10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_Vista10ActionPerformed(evt);
            }
        });

        jLabel3.setText("Hora fin:");

        HoraInicioCrearActividad_Vista10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraInicioCrearActividad_Vista10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(Cancelar_Vista10)
                .addGap(50, 50, 50)
                .addComponent(Aceptar_Vista10)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HoraInicioCrearActividad_Vista10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaCrearActividad_Vista10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoraFinCrearActividad_Vista10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(HoraInicioCrearActividad_Vista10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(HoraFinCrearActividad_Vista10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FechaCrearActividad_Vista10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar_Vista10)
                    .addComponent(Cancelar_Vista10))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfContraseña3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña3ActionPerformed

    private void tfContraseña7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña7ActionPerformed

    private void Aceptar_Vista10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar_Vista10ActionPerformed
        Vista_11 v11 = new Vista_11();
        v11.show();
        this.dispose();
    }//GEN-LAST:event_Aceptar_Vista10ActionPerformed

    private void Cancelar_Vista10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_Vista10ActionPerformed
        // TODO add your handling code here:
        Vista_9 v9 = new Vista_9();
        v9.show();
        this.dispose();
    }//GEN-LAST:event_Cancelar_Vista10ActionPerformed

    private void HoraFinCrearActividad_Vista10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraFinCrearActividad_Vista10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraFinCrearActividad_Vista10ActionPerformed

    private void HoraInicioCrearActividad_Vista10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraInicioCrearActividad_Vista10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraInicioCrearActividad_Vista10ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_10().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar_Vista10;
    private javax.swing.JButton Cancelar_Vista10;
    private com.toedter.calendar.JDateChooser FechaCrearActividad_Vista10;
    private javax.swing.JTextField HoraFinCrearActividad_Vista10;
    private javax.swing.JTextField HoraInicioCrearActividad_Vista10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfContraseña3;
    private javax.swing.JTextField tfContraseña7;
    private javax.swing.JTextField tfUsuario1;
    // End of variables declaration//GEN-END:variables
}
