/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_isi.ii;


import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author ramon
 */
public class Vista_17 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana8
     */
    public Vista_17() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsuario1 = new javax.swing.JTextField();
        tfContraseña3 = new javax.swing.JTextField();
        tfContraseña7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaParcelas_Vista17 = new javax.swing.JList<>();
        label_Vista17 = new javax.swing.JLabel();
        Descuento_Vista17 = new javax.swing.JTextField();
        aceptar_Vista17 = new javax.swing.JButton();

        tfContraseña3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña3ActionPerformed(evt);
            }
        });

        tfContraseña7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListaParcelas_Vista17.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Parcela 1", "Parcela 2", "Parcela 3", "Parcela 4", "Parcela 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaParcelas_Vista17.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ListaParcelas_Vista17AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(ListaParcelas_Vista17);

        label_Vista17.setText("Establecer descuento:");

        Descuento_Vista17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Descuento_Vista17ActionPerformed(evt);
            }
        });

        aceptar_Vista17.setBackground(new java.awt.Color(0, 51, 255));
        aceptar_Vista17.setForeground(new java.awt.Color(255, 255, 255));
        aceptar_Vista17.setText("Aceptar");
        aceptar_Vista17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_Vista17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(label_Vista17)
                        .addGap(18, 18, 18)
                        .addComponent(Descuento_Vista17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(aceptar_Vista17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Vista17)
                    .addComponent(Descuento_Vista17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptar_Vista17)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfContraseña3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña3ActionPerformed

    private void tfContraseña7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña7ActionPerformed

    private void aceptar_Vista17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_Vista17ActionPerformed
        // TODO add your handling code here
        Vista_9 v9 = new Vista_9();
        v9.show();
        this.dispose();
    }//GEN-LAST:event_aceptar_Vista17ActionPerformed

    private void ListaParcelas_Vista17AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ListaParcelas_Vista17AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaParcelas_Vista17AncestorAdded

    private void Descuento_Vista17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Descuento_Vista17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Descuento_Vista17ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_17().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descuento_Vista17;
    private javax.swing.JList<String> ListaParcelas_Vista17;
    private javax.swing.JButton aceptar_Vista17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Vista17;
    private javax.swing.JTextField tfContraseña3;
    private javax.swing.JTextField tfContraseña7;
    private javax.swing.JTextField tfUsuario1;
    // End of variables declaration//GEN-END:variables
}
