/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_isi.ii;


import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author ramon
 */
public class Vista_13 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana8
     */
    public Vista_13() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsuario1 = new javax.swing.JTextField();
        tfContraseña3 = new javax.swing.JTextField();
        tfContraseña7 = new javax.swing.JTextField();
        Emparejar_Vista13 = new javax.swing.JButton();
        AnotarGanador_Vista13 = new javax.swing.JButton();
        Recuento_Vista13 = new javax.swing.JButton();
        Cancelar_Vista13 = new javax.swing.JButton();
        FinActividad_Vista13 = new javax.swing.JButton();

        tfContraseña3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña3ActionPerformed(evt);
            }
        });

        tfContraseña7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Emparejar_Vista13.setBackground(new java.awt.Color(0, 51, 255));
        Emparejar_Vista13.setForeground(new java.awt.Color(255, 255, 255));
        Emparejar_Vista13.setText("Emparejar");
        Emparejar_Vista13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emparejar_Vista13ActionPerformed(evt);
            }
        });

        AnotarGanador_Vista13.setBackground(new java.awt.Color(0, 51, 255));
        AnotarGanador_Vista13.setForeground(new java.awt.Color(255, 255, 255));
        AnotarGanador_Vista13.setText("Anotar ganador");
        AnotarGanador_Vista13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnotarGanador_Vista13ActionPerformed(evt);
            }
        });

        Recuento_Vista13.setBackground(new java.awt.Color(0, 51, 255));
        Recuento_Vista13.setForeground(new java.awt.Color(255, 255, 255));
        Recuento_Vista13.setText("Hacer recuento");
        Recuento_Vista13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recuento_Vista13ActionPerformed(evt);
            }
        });

        Cancelar_Vista13.setBackground(new java.awt.Color(0, 51, 255));
        Cancelar_Vista13.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar_Vista13.setText("Cancelar");
        Cancelar_Vista13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_Vista13ActionPerformed(evt);
            }
        });

        FinActividad_Vista13.setBackground(new java.awt.Color(0, 51, 255));
        FinActividad_Vista13.setForeground(new java.awt.Color(255, 255, 255));
        FinActividad_Vista13.setText("Finalizar actividad");
        FinActividad_Vista13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinActividad_Vista13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AnotarGanador_Vista13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Emparejar_Vista13, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(Recuento_Vista13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FinActividad_Vista13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(Cancelar_Vista13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Emparejar_Vista13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AnotarGanador_Vista13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Recuento_Vista13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FinActividad_Vista13)
                .addGap(16, 16, 16)
                .addComponent(Cancelar_Vista13)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfContraseña3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña3ActionPerformed

    private void tfContraseña7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña7ActionPerformed

    private void Emparejar_Vista13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emparejar_Vista13ActionPerformed
        // TODO add your handling code here:
        Vista_14 v14 = new Vista_14();
        v14.show();
        this.dispose();
    }//GEN-LAST:event_Emparejar_Vista13ActionPerformed

    private void AnotarGanador_Vista13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnotarGanador_Vista13ActionPerformed
        // TODO add your handling code here:
        Vista_15 v15 = new Vista_15();
        v15.show();
        this.dispose();
    }//GEN-LAST:event_AnotarGanador_Vista13ActionPerformed

    private void Recuento_Vista13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recuento_Vista13ActionPerformed
        // TODO add your handling code here:
        Vista_16 v16 = new Vista_16();
        v16.show();
        this.dispose();
    }//GEN-LAST:event_Recuento_Vista13ActionPerformed

    private void FinActividad_Vista13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinActividad_Vista13ActionPerformed
        // TODO add your handling code here:
        
        //Popup de confirmacion?
        Vista_9 v9 = new Vista_9();
        v9.show();
        this.dispose();
        
    }//GEN-LAST:event_FinActividad_Vista13ActionPerformed

    private void Cancelar_Vista13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_Vista13ActionPerformed
        // TODO add your handling code here:
        Vista_9 v9 = new Vista_9();
        v9.show();
        this.dispose();
    }//GEN-LAST:event_Cancelar_Vista13ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_13().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnotarGanador_Vista13;
    private javax.swing.JButton Cancelar_Vista13;
    private javax.swing.JButton Emparejar_Vista13;
    private javax.swing.JButton FinActividad_Vista13;
    private javax.swing.JButton Recuento_Vista13;
    private javax.swing.JTextField tfContraseña3;
    private javax.swing.JTextField tfContraseña7;
    private javax.swing.JTextField tfUsuario1;
    // End of variables declaration//GEN-END:variables
}
