/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_isi.ii;

import modelo.Camping;
import modelo.Cliente;
import java.awt.Dimension;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Trabajador;

/**
 *
 * @author ramon
 */
public class Vista_1 extends javax.swing.JFrame {
    /**
     * Creates new form Ventana8
     */
    public Vista_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlContraseña = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        tfContraseña = new javax.swing.JTextField();
        jbCancelar = new javax.swing.JButton();
        jbEntrarCliente = new javax.swing.JButton();
        jbEntrarTrabajador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlTitulo.setText("            LOGIN ");

        jlUsuario.setText("Usuario");

        jlContraseña.setText("Contraseña");

        tfContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseñaActionPerformed(evt);
            }
        });

        jbCancelar.setBackground(new java.awt.Color(0, 51, 255));
        jbCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbEntrarCliente.setBackground(new java.awt.Color(0, 51, 255));
        jbEntrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jbEntrarCliente.setLabel("Cliente");
        jbEntrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarClienteActionPerformed(evt);
            }
        });

        jbEntrarTrabajador.setBackground(new java.awt.Color(0, 51, 255));
        jbEntrarTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        jbEntrarTrabajador.setLabel("Trabajador");
        jbEntrarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfContraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jbCancelar)
                .addGap(18, 18, 18)
                .addComponent(jbEntrarCliente)
                .addGap(18, 18, 18)
                .addComponent(jbEntrarTrabajador)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlTitulo)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuario)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlContraseña)
                    .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbEntrarCliente)
                    .addComponent(jbEntrarTrabajador))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        
        setVisible(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbEntrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarClienteActionPerformed
        Camping a = Camping.getInstancia();
        try {
            a.cargarDatos();
        } catch (ParseException ex) {
            Logger.getLogger(Vista_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        Cliente c =  Cliente.IniciarSesion(tfUsuario.getText(), tfContraseña.getText());
        
        if(c == null)
        {
            JOptionPane.showMessageDialog(null, "Usuario no registrado", "Inane error",JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {
            Vista_2 vista_2 = new Vista_2(a,c);
            setVisible(false);
            vista_2.setSize(412, 700);
            vista_2.setPreferredSize(new Dimension(412, 800));
            vista_2.setVisible(true);
        }
    }//GEN-LAST:event_jbEntrarClienteActionPerformed

    private void tfContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseñaActionPerformed
            

    }//GEN-LAST:event_tfContraseñaActionPerformed

    private void jbEntrarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarTrabajadorActionPerformed
        Camping a = Camping.getInstancia();
        try {
            a.cargarDatos();
        } catch (ParseException ex) {
            Logger.getLogger(Vista_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        Trabajador t =  Trabajador.IniciarSesion(tfUsuario.getText(), tfContraseña.getText());
        
        if(t == null)
        {
            JOptionPane.showMessageDialog(null, "Usuario no registrado", "Inane error",JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {
            Vista_9 v9 = new Vista_9(a);
            v9.show();
            this.dispose();
        }
    }//GEN-LAST:event_jbEntrarTrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_1().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEntrarCliente;
    private javax.swing.JButton jbEntrarTrabajador;
    private javax.swing.JLabel jlContraseña;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JTextField tfContraseña;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
