/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_isi.ii;

import modelo.Camping;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Actividad;
import modelo.Cliente;
import modelo.ReservaActividad;

/**
 *
 * @author ramon
 */
public class Vista_25 extends javax.swing.JFrame {
    private Camping c;
    private Cliente clog;
    private ReservaActividad resA_Actual;
    private String horaActual;
    private Actividad actividad;
    /**
     * Creates new form Ventana8
     */
    public Vista_25(Camping c, Cliente clog, Actividad actividad) {
        initComponents();
        this.c = c;
        this.clog = clog;
        this.actividad = actividad;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsuario1 = new javax.swing.JTextField();
        tfContraseña3 = new javax.swing.JTextField();
        tfContraseña7 = new javax.swing.JTextField();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        LabelHoraEntrada_Vista25 = new javax.swing.JLabel();
        Hora_Vista25 = new javax.swing.JTextField();
        Participar_Vista25 = new javax.swing.JButton();
        Cancelar_Vista25 = new javax.swing.JButton();

        tfContraseña3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña3ActionPerformed(evt);
            }
        });

        tfContraseña7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelHoraEntrada_Vista25.setText("Hora de entrada:");

        Hora_Vista25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hora_Vista25ActionPerformed(evt);
            }
        });

        Participar_Vista25.setBackground(new java.awt.Color(0, 51, 255));
        Participar_Vista25.setForeground(new java.awt.Color(255, 255, 255));
        Participar_Vista25.setText("Participar");
        Participar_Vista25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Participar_Vista25ActionPerformed(evt);
            }
        });

        Cancelar_Vista25.setBackground(new java.awt.Color(0, 51, 255));
        Cancelar_Vista25.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar_Vista25.setText("Cancelar");
        Cancelar_Vista25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_Vista25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelHoraEntrada_Vista25)
                    .addComponent(Cancelar_Vista25))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Participar_Vista25)
                    .addComponent(Hora_Vista25, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHoraEntrada_Vista25)
                    .addComponent(Hora_Vista25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Participar_Vista25)
                    .addComponent(Cancelar_Vista25))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfContraseña3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña3ActionPerformed

    private void tfContraseña7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña7ActionPerformed

    private void Participar_Vista25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Participar_Vista25ActionPerformed
        // TODO add your handling code here:
        horaActual = Hora_Vista25.getText();
        String[] auxActual = horaActual.split(":");
        String[] auxActividadInit = actividad.getHoraInicio().split(":");
        String[] auxActividadFin = actividad.getHoraFin().split(":");
        if((Integer.parseInt(auxActual[0])>Integer.parseInt(auxActividadInit[0]))
           && (Integer.parseInt(auxActual[0])< Integer.parseInt(auxActividadFin[0])))
        {
           resA_Actual=new ReservaActividad(actividad.getFecha(),actividad,horaActual,null,clog);
           actividad.setReserva(resA_Actual);
           c.addReservaActividad(resA_Actual);
           Vista_2 v2 = new Vista_2(c,clog);
           v2.show();
           this.dispose();
        }
        else if((Integer.parseInt(auxActual[0])==Integer.parseInt(auxActividadInit[0]))
           && (Integer.parseInt(auxActual[0])== Integer.parseInt(auxActividadFin[0])))
        {
            if((Integer.parseInt(auxActual[1])>=Integer.parseInt(auxActividadInit[1]))
           && (Integer.parseInt(auxActual[1])<= Integer.parseInt(auxActividadFin[1])))
            {
     n           resA_Actual=new ReservaActividad(actividad.getFecha(),actividad,horaActual,null,clog);
                actividad.setReserva(resA_Actual);
                c.addReservaActividad(resA_Actual);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "HORA INVALIDA", "Inane error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_Participar_Vista25ActionPerformed

    private void Cancelar_Vista25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_Vista25ActionPerformed
        // TODO add your handling code here:
        Vista_24 v24 = new Vista_24(c,clog);
        v24.show();
        this.dispose();
    }//GEN-LAST:event_Cancelar_Vista25ActionPerformed

    private void Hora_Vista25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hora_Vista25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hora_Vista25ActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar_Vista25;
    private javax.swing.JTextField Hora_Vista25;
    private javax.swing.JLabel LabelHoraEntrada_Vista25;
    private javax.swing.JButton Participar_Vista25;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JTextField tfContraseña3;
    private javax.swing.JTextField tfContraseña7;
    private javax.swing.JTextField tfUsuario1;
    // End of variables declaration//GEN-END:variables
    
}
