/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_isi.ii;

import modelo.Camping;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Actividad;

/**
 *
 * @author ramon
 */
public class Vista_12 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana8
     */
    public Vista_12() {
        initComponents();
        DefaultListModel<String> modelo = new DefaultListModel<>();
        ListaActividades_Vista12.setModel(modelo);
        Camping c = Camping.getInstancia();
        ArrayList<Actividad> actividades = c.getActividades();
        for(int i = 0; i < actividades.size(); ++i){
           modelo.addElement(actividades.get(i).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsuario1 = new javax.swing.JTextField();
        tfContraseña3 = new javax.swing.JTextField();
        tfContraseña7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaActividades_Vista12 = new javax.swing.JList<>();
        Seleccionar_Vista12 = new javax.swing.JButton();
        Atras_Vista13 = new javax.swing.JButton();

        tfContraseña3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña3ActionPerformed(evt);
            }
        });

        tfContraseña7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListaActividades_Vista12.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Piscina 12:00 24/07/2023", "Fronton 18:00 25/08/2023", "Juegos de mesa 11:00 15/09/2023" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaActividades_Vista12);

        Seleccionar_Vista12.setBackground(new java.awt.Color(0, 51, 255));
        Seleccionar_Vista12.setForeground(new java.awt.Color(255, 255, 255));
        Seleccionar_Vista12.setText("Seleccionar");
        Seleccionar_Vista12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccionar_Vista12ActionPerformed(evt);
            }
        });

        Atras_Vista13.setBackground(new java.awt.Color(0, 51, 255));
        Atras_Vista13.setForeground(new java.awt.Color(255, 255, 255));
        Atras_Vista13.setText("Atrás");
        Atras_Vista13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atras_Vista13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(Atras_Vista13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Seleccionar_Vista12)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seleccionar_Vista12)
                    .addComponent(Atras_Vista13))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfContraseña3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña3ActionPerformed

    private void tfContraseña7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña7ActionPerformed

    private void Seleccionar_Vista12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccionar_Vista12ActionPerformed
        if(ListaActividades_Vista12.getSelectedValue() == null)
            System.out.println("SELECCIONA UNA ACTIVIDAD");
        else
        {
            Vista_13 v13 = new Vista_13();
            v13.show();
            this.dispose();
        }
            
    }//GEN-LAST:event_Seleccionar_Vista12ActionPerformed

    private void Atras_Vista13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atras_Vista13ActionPerformed
        // TODO add your handling code here:
        Vista_9 v9 = new Vista_9();
        v9.show();
        this.dispose();
    }//GEN-LAST:event_Atras_Vista13ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_12().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras_Vista13;
    private javax.swing.JList<String> ListaActividades_Vista12;
    private javax.swing.JButton Seleccionar_Vista12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfContraseña3;
    private javax.swing.JTextField tfContraseña7;
    private javax.swing.JTextField tfUsuario1;
    // End of variables declaration//GEN-END:variables
}
